//
// Created by Rijad on 29-Jul-18.
//

#ifndef ASTL_INCLUDE_ALGORITHM_HPP
#define ASTL_INCLUDE_ALGORITHM_HPP

#include "internal/accumulate.hpp"
#include "internal/adjacent_difference.hpp"
#include "internal/adjacent_find.hpp"
#include "internal/all_of.hpp"
#include "internal/any_of.hpp"
#include "internal/binary_search.hpp"
#include "internal/clamp.hpp"
#include "internal/copy.hpp"
#include "internal/count.hpp"
#include "internal/dynamic_programing.hpp"
#include "internal/equal.hpp"
#include "internal/equal_range.hpp"
#include "internal/erase_if.hpp"
#include "internal/fill.hpp"
#include "internal/find.hpp"
#include "internal/for_each.hpp"
#include "internal/gather.hpp"
#include "internal/heap.hpp"
#include "internal/inner_product.hpp"
#include "internal/inplace_merge.hpp"
#include "internal/iota.hpp"
#include "internal/is_contained.hpp"
#include "internal/is_palindrome.hpp"
#include "internal/lexicographical_compare.hpp"
#include "internal/lower_bound.hpp"
#include "internal/max.hpp"
#include "internal/merge.hpp"
#include "internal/min.hpp"
#include "internal/minmax_element.hpp"
#include "internal/mismatch.hpp"
#include "internal/move.hpp"
#include "internal/none_of.hpp"
#include "internal/partial_sum.hpp"
#include "internal/partition.hpp"
#include "internal/permutation.hpp"
#include "internal/permutation_combinations.hpp"
#include "internal/reduce.hpp"
#include "internal/remove.hpp"
#include "internal/replace.hpp"
#include "internal/reverse.hpp"
#include "internal/rotate.hpp"
#include "internal/scan.hpp"
#include "internal/search.hpp"
#include "internal/select.hpp"
#include "internal/set_algos.hpp"
#include "internal/shift.hpp"
#include "internal/slide.hpp"
#include "internal/sort.hpp"
#include "internal/starts_ends.hpp"
#include "internal/swap.hpp"
#include "internal/transform.hpp"
#include "internal/trim.hpp"
#include "internal/unique.hpp"
#include "internal/upper_bound.hpp"

#endif// ASTL_INCLUDE_ALGORITHM_HPP
